# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lojinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lojinha
  pod 'UIScrollView-InfiniteScroll'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'LojinhaTests' do
    inherit! :search_paths
    # Tests
    pod 'Nimble'
    pod 'Quick'
    
  end

  target 'LojinhaUITests' do
    inherit! :search_paths
    
    pod 'Nimble'
    pod 'Quick'
  end

end
